### ISSUE TITLE
Attention :)

### ISSUE THREAD

**Issue by JacquesDurand** [riwalenn/Projet-5#69]
Hello, étudiant OpenClassrooms en attaque du projet 5 de blog en php, je suis tombé sur ton repo par curiosité, et n'ai pas pu m'empêcher de remarquer que le mot de passe admin de ton blog actuellement en ligne est toujours commité en dur dans ton README

**Comment by riwalenn** [comment]
Bonsoir, je te remercie mais la bdd que je mets en ligne est complétement différente et les mots de passe ainsi que les users aussi :)

**Comment by JacquesDurand** [comment]
Je te laisse vérifier, mais j'ai pu me connecter à ton espace administrateur sur https://projet5.riwalennbas.com/index.php avec ton email et le mot de passe admin que tu donnes dans ton readme :thinking:

**Comment by riwalenn** [comment]
Ah oui effectivement, c'est bizarre parce que je suis censée avoir une adresse email unique et je peux me connecter avec un autre mot de passe ^^'.. ben merci pour le tip je vais modifier cela de suite :)
